[package]
name = "percolation"
version = "0.1.0"
edition = "2021"
publish = ["afo"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
threadpool = "1.8.1"
clap = { version = "4", features = ["derive"] }